name: SemiRP
version: 1.1.0
api-version: '1.20'
author: Trisout
main: fr.trisout.semirp.Main
commands:
  broadcast:
    permission: semirp.broadcast.use
    description: broadcast command
  annonce:
    permission: semirp.annonce.use
    description: annonce command
  mairie:
    description: mairie command
    aliases: [spawn, sp]
