name: SemiRP
version: 1.0.1
api-version: '1.20'
main: fr.trisout.semirp.Main
commands:
  broadcast:
    permission: semirp.broadcast.use
    description: broadcast command
  annonce:
    permission: semirp.annonce.use
    description: annonce command
  mairie:
    description: Se téléporter a la mairie